/// FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

export const SHEETS_SYNC = 'SHEETS_SYNC';

export const SHEETS_ON_VALUE = 'SHEETS_ON_VALUE';
export const SHEETS_ON_CHILD_ADDED = "SHEETS_ON_CHILD_ADDED";
export const SHEETS_ON_CHILD_REMOVED = 'SHEETS_ON_CHILD_REMOVED';
export const SHEETS_ON_CHILD_CHANGED = 'SHEETS_ON_CHILD_CHANGED';
export const SHEETS_ON_CHILD_MOVED = 'SHEETS_ON_CHILD_MOVED';

export const SHEET_EDIT = 'SHEET_EDIT';
export const SHEET_EDIT_ON_VALUE = 'SHEET_EDIT_ON_VALUE';

export const SHEET_SAVE_UPDATES = 'SHEET_SAVE_UPDATES';
export const SHEET_CANCEL_UPDATES = 'SHEET_CANCEL_UPDATES';
export const SHEET_HANDLE_CHANGE = 'SHEET_HANDLE_CHANGE';

export const SHEET_BLOCK_DISPLAY = 'SHEET_BLOCK_DISPLAY';
export const SHEET_BLOCK_ON_VALUE = 'SHEET_BLOCK_ON_VALUE';
export const SHEET_UPDATE = 'SHEET_UPDATE';

export const DICTIONARY_ON_VALUE = "DICTIONARY_ON_VALUE";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
